on: 
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps: 
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOCKEN}}
      - name: "build image"
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/image2 .

      - name: "push to docker hup"
        run: docker push ${{secrets.DOCKER_USERNAME}}/image2 

