on: 
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest


    steps: 
      - uses: actions/checkout@v3

      - name: "login to docker hub"
        run: docker login --username shymaaelhawary1 --password dckr_pat_y3wJFIcKRhjWafeS-g96tGOx90w

